# Inside _config.yml
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap # If you're using other plugins, keep them here
remote_theme: pages-themes/cayman@v0.2.0

# Include your custom CSS
custom_css: assets/css/dark-theme.css
title: mc-1st.ro
description: Patch Notes
